CountingMethod
MaxTarn/ValhallaVault pull request #37
Opened 2024-03-11 21:14 UTC by Henk01

2024-03-12 13:50 UTC, LudvigBergerud approved these changes
nice

2024-03-12 15:32 UTC, MaxTarn requested changes
metod ska inte kasta en exception när något blir null, utan ska istället returnera ett null svar

2024-03-14 11:16 UTC, MaxTarn requested changes
Problem kvarstår. I AnswerRepo så kastar du exception. Istället för att kasta exception kan du istället returnera null.  Så behöver inte varje call till repot vara i en try-catch

2024-03-15 15:31 UTC, MaxTarn approved these changes
👍

2024-03-15 16:45 UTC, merged